### ISSUE TITLE
Support VGGnet

### ISSUE THREAD

**Issue by shidong-ai** [doody1986/DNNMark#18]

**Comment by pyotr777** [comment]
Hi!
I am working on VGG-16. Created a new benchmark (.cc) and .dnnmark file with network description.
It compiles OK, but when I run it I get an error.

```
...
I1212 14:44:36.465998 30679 dnnmark.cc:465] DNNMark: Running convolution forward: STARTED
I1212 14:44:36.466193 30679 dnnmark.cc:468] DNNMark: Running convolution forward: FINISHED
I1212 14:44:36.466200 30679 dnnmark.cc:501] DNNMark: Running BatchNormalization forward: STARTED
I1212 14:44:36.466413 30679 dnnmark.cc:504] DNNMark: Running BatchNormalization forward: FINISHED
I1212 14:44:36.466418 30679 dnnmark.cc:483] DNNMark: Running Activation forward: STARTED
I1212 14:44:36.466500 30679 dnnmark.cc:486] DNNMark: Running Activation forward: FINISHED
I1212 14:44:36.466506 30679 dnnmark.cc:507] DNNMark: Running Dropout forward: STARTED
CUDNN Error at /home/peter/DNNMark/core/include/dnn_wrapper.h717CUDNN_STATUS_BAD_PARAM
I1212 14:44:36.466570 30679 data_manager.h:53] Free Data chunk of size 51200
CUDA Error at /home/peter/DNNMark/core/include/data_manager.h56
driver shutting down
```

I am on the latest commit of `develop` branch.

**Comment by shidong-ai** [comment]
@pyotr777 
Hi, I fixed one bug related to the issue you found and committed the code. You can use the latest develop branch now.
Let me know if there are any other problems!
Thanks for finding this issue.

Shi

**Comment by pyotr777** [comment]
Thank you!
The error is gone.

**Comment by shidong-ai** [comment]
@pyotr777 
Hi Peter,

Could you start a pull request with your updates?
Thanks a lot!

Shi

**Comment by pyotr777** [comment]
Hi Shi,

Sorry for the delay. I have to prepare a new branch, because the branch I currently use has lots of scripts and other files I use in my research, that seem to be unnecessary for other DNNMark users.
Shall I use “develop” as the target (base) branch?

I think I shall be ready within few hours.

Regards,
Peter

**Comment by shidong-ai** [comment]
@pyotr777 
Yes. the "develop" should be the base branch.
Thanks!

Shi

**Comment by shidong-ai** [comment]
Pull request is reviewed and merged
